## Basics of R

### Help

In [1]:
# Help function: this shows for us how to use a command or others informations.

# help(mean) or ?mean

### Expressions 

In [2]:
# Assignment of values

x <- 2 #We use <- to assign values to x 
y <- c(2, 4, 6) # We use c() function to concatenate values

x #This shows x
y #This shows y

[1] 2

[1] 2 4 6

### Numbers


In [3]:
r <- 1 # double precision real number
i <- 1L # integer number
c <- 1i # complex number

p <- Inf #Inf = infinite

q <- NaN # NaN is a unidentified value number

###  Attributes

In [4]:
# Names, dimnames
# Dimenssion
# Class
# Lenght
# Other user-defined attributes

#attributes() function: to acess attributes

#example

attributes(mtcars)

#specific attributes
names(mtcars) 
row.names(mtcars)
class(mtcars)

$names
 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"

$row.names
 [1] "Mazda RX4"           "Mazda RX4 Wag"       "Datsun 710"         
 [4] "Hornet 4 Drive"      "Hornet Sportabout"   "Valiant"            
 [7] "Duster 360"          "Merc 240D"           "Merc 230"           
[10] "Merc 280"            "Merc 280C"           "Merc 450SE"         
[13] "Merc 450SL"          "Merc 450SLC"         "Cadillac Fleetwood" 
[16] "Lincoln Continental" "Chrysler Imperial"   "Fiat 128"           
[19] "Honda Civic"         "Toyota Corolla"      "Toyota Corona"      
[22] "Dodge Challenger"    "AMC Javelin"         "Camaro Z28"         
[25] "Pontiac Firebird"    "Fiat X1-9"           "Porsche 914-2"      
[28] "Lotus Europa"        "Ford Pantera L"      "Ferrari Dino"       
[31] "Maserati Bora"       "Volvo 142E"         

$class
[1] "data.frame"

[1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"

[1] "Mazda RX4"           "Mazda RX4 Wag"       "Datsun 710"         
 [4] "Hornet 4 Drive"      "Hornet Sportabout"   "Valiant"            
 [7] "Duster 360"          "Merc 240D"           "Merc 230"           
[10] "Merc 280"            "Merc 280C"           "Merc 450SE"         
[13] "Merc 450SL"          "Merc 450SLC"         "Cadillac Fleetwood" 
[16] "Lincoln Continental" "Chrysler Imperial"   "Fiat 128"           
[19] "Honda Civic"         "Toyota Corolla"      "Toyota Corona"      
[22] "Dodge Challenger"    "AMC Javelin"         "Camaro Z28"         
[25] "Pontiac Firebird"    "Fiat X1-9"           "Porsche 914-2"      
[28] "Lotus Europa"        "Ford Pantera L"      "Ferrari Dino"       
[31] "Maserati Bora"       "Volvo 142E"

[1] "data.frame"

### Classes

In [5]:
#Atomic classes
 # Numeric
    class(r) #real number

 # Integer
    class(i) #integer

 # Complex
    z = 1 + 1i #complex number
    class(z)

 # Logical
    class(2 > 1) #logical expressions

 # Character
    w <- "word"
    class(w) #sequence of characters

#Check classes:

is.logical(z)

is.character(w)

#Convertion:

class(as.numeric(i)) #as.numeric(i) converts i in numeric

[1] "numeric"

[1] "integer"

[1] "complex"

[1] "logical"

[1] "character"

[1] FALSE

[1] TRUE

[1] "numeric"

### Vectors

In [6]:
v <- vector("numeric", 5) #empty vector
co <- c(1, 1.2, 50)
ig <- 1:10 #integers

c(v, co) #combining vectors

#index

co[2]
co[4]

[1]  0.0  0.0  0.0  0.0  0.0  1.0  1.2 50.0

[1] 1.2

[1] NA

### Arithmetics

In [7]:
a <- c(2, 3, 5, 7)
b <- c(1, 2, 3, 4)

2 * a    
a * b
a / b
a + b
a - b

[1]  4  6 10 14

[1]  2  6 15 28

[1] 2.000000 1.500000 1.666667 1.750000

[1]  3  5  8 11

[1] 1 1 2 3

### Lists

In [8]:
#Lists can contain different classes of elements

list1 <- list(1L, "object", 3 + 2i, 5.0, 1:7)

#To access elements:

list1[[2]]

list1[[5]][3]

[1] "object"

[1] 3

In [9]:
#Creating lists combining vectors
v1 <- c(1, 15, 72)
v2 <- c('A', 'B', 'C')

list2 <- list(v1, v2)

list2
list2[1] #list slicing
list2[[1]] #member reference

[[1]]
[1]  1 15 72

[[2]]
[1] "A" "B" "C"

[[1]]
[1]  1 15 72

[1]  1 15 72

In [10]:
#Inserting or replacing an element
list3 <- list(2, 4, 'b', 5L)
list3

list3[[3]][2] <- 'hello'
list3

[[1]]
[1] 2

[[2]]
[1] 4

[[3]]
[1] "b"

[[4]]
[1] 5

[[1]]
[1] 2

[[2]]
[1] 4

[[3]]
[1] "b"     "hello"

[[4]]
[1] 5

In [11]:
#Named list elements

list4 <- list(fruits = c('banana', 'orange', 'avocado', 'apple'), desserts = c('cake', 'ice cream', 'mousse'))

list4

$fruits
[1] "banana"  "orange"  "avocado" "apple"  

$desserts
[1] "cake"      "ice cream" "mousse"

In [12]:
list4$fruits
list4[['fruits']]

[1] "banana"  "orange"  "avocado" "apple"

[1] "banana"  "orange"  "avocado" "apple"

In [13]:
list4['desserts'] #list slicing


$desserts
[1] "cake"      "ice cream" "mousse"

In [14]:
list4[c('desserts', 'fruits')]

$desserts
[1] "cake"      "ice cream" "mousse"   

$fruits
[1] "banana"  "orange"  "avocado" "apple"

In [15]:
attach(list4)
desserts

[1] "cake"      "ice cream" "mousse"

In [16]:
detach(list4)
list4

$fruits
[1] "banana"  "orange"  "avocado" "apple"  

$desserts
[1] "cake"      "ice cream" "mousse"

### Matrices

In [17]:
m1 <- matrix(nrow=2, ncol=3) #empty matrix
m1

dim(m1)

attributes(m1)

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

[1] 2 3

$dim
[1] 2 3

In [18]:
m2 <- matrix(1:6, nrow=2, ncol=3)
m2

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [19]:
m3 <- 1:6 #vector 1D
m3

dim(m3) <- c(2,3) #now a 2x3 matrix
m3 

[1] 1 2 3 4 5 6

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [20]:
#biding columns

m4_1 <- 1:3
m4_2 <- 4:6

cbind(m4_1, m4_2)

#biding rows

rbind(m4_1,m4_2)

m4_1 m4_2
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1] [,2] [,3]
m4_1 1    2    3   
m4_2 4    5    6

In [21]:
m5 <- matrix(1:6, nrow=2, ncol=3, byrow=TRUE)
m5

#To extract rows and columns
m5[1,2]
m5[2,2]

m5[,3]
m5[1,]

m5[,c(1,2)]

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

[1] 2

[1] 5

[1] 3 6

[1] 1 2 3

[,1] [,2]
[1,] 1    2   
[2,] 4    5

In [22]:
#To give a name to the rows and columns

dimnames(m5) <- list(c('row1', 'row2'), c('col1','col2','col3'))
m5

m5["row2", "col3"]

col1 col2 col3
row1 1    2    3   
row2 4    5    6

[1] 6

In [23]:
t(m5) #To transpose the matrix
c(m5) #Vector

row1 row2
col1 1    4   
col2 2    5   
col3 3    6

[1] 1 4 2 5 3 6

### Factors

In [24]:
#Used to represent categorical data

#Exemple: points: blue or red

color <- factor(c('blue', 'red', 'red','red','blue', 'blue', 'red'))
color

table(color)

#Ordered factors
color <- factor(c('blue', 'red', 'red','red','blue', 'blue', 'red'), levels=c('red', 'blue'))
color


[1] blue red  red  red  blue blue red 
Levels: blue red

color
blue  red 
   3    4 

[1] blue red  red  red  blue blue red 
Levels: red blue

### Data frames

In [25]:
df <- data.frame(
    name =c("Mario", "Beatrice", "Jhon"),
    gender = c("male","female", "male"),
    age = c(31, 35, 36)
)

df

row.names(df) <- c("Spain", "Brazil", "Portugal")
df

name     gender age
1 Mario    male   31 
2 Beatrice female 35 
3 Jhon     male   36

name     gender age
Spain    Mario    male   31 
Brazil   Beatrice female 35 
Portugal Jhon     male   36

In [26]:
#Extracting values

df[1,3]

df['Spain','age']

df['Spain', 'name']

[1] 31

[1] 31

[1] Mario
Levels: Beatrice Jhon Mario

In [27]:
#DF column slice

df['name']

df[1]

name    
Spain    Mario   
Brazil   Beatrice
Portugal Jhon

name    
Spain    Mario   
Brazil   Beatrice
Portugal Jhon

In [28]:
#DF column vector

df$name

df$age

df[[3]]

[1] Mario    Beatrice Jhon    
Levels: Beatrice Jhon Mario

[1] 31 35 36

[1] 31 35 36

In [29]:
#Some functions

head(df) #first 6 rows
tail(df) #last 6 rows

nrow(df)
ncol(df)

name     gender age
Spain    Mario    male   31 
Brazil   Beatrice female 35 
Portugal Jhon     male   36

name     gender age
Spain    Mario    male   31 
Brazil   Beatrice female 35 
Portugal Jhon     male   36

[1] 3

[1] 3

### Importing and exporting data

In [30]:
write.csv(df,'data_frame_example.csv')
df_data <-read.csv('data_frame_example.csv', head=TRUE)

df_data

X        name     gender age
1 Spain    Mario    male   31 
2 Brazil   Beatrice female 35 
3 Portugal Jhon     male   36